### ISSUE TITLE
Repository licence

### ISSUE THREAD

**Issue by gustavi** [scipython/scipython_maths#6]
Hello,

I currently using an algorithm (https://github.com/scipython/scipython-maths/blob/master/poisson_disc_sampled_noise/poisson.py) from this repository inside a project. Could you provide a license to this repository ?

https://choosealicense.com/ and https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository may help you. Thank you a lot.

**Comment by xnx** [comment]
Fair enough – MIT Licence added.
I'm glad you find the code useful to you.
